[package]
name = "apibara-sink-benchmark"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "apibara-sink-benchmark"
path = "src/bin.rs"

[dependencies]
apibara-observability = { path = "../../observability" }
apibara-sink-common = { path = "../sink-common" }
apibara-dna-protocol = { path = "../../dna/protocol" }
async-trait.workspace = true
byte-unit.workspace = true
clap.workspace = true
error-stack.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[target.'cfg(not(windows))'.dependencies]
jemallocator.workspace = true
