[workspace]
members = [
    "core",
    "observability",
    "node",
    "sdk",
    "starknet",
    "sink-common",
    "sink-webhook",
    "sink-mongo",
    "sink-parquet",
    "sink-postgres",
    "examples/starknet-simple",
]

[patch.crates-io]
# Fixes related to copying file permissions/mode when building.
# Can be removed when PR have been merged and released.
# https://github.com/denoland/rusty_v8/pull/1244
v8 = { git = "https://github.com/fracek/rusty_v8.git", rev = "8140a1a6d7a8296d68dfcf7efb6f30b9f1ae04a" }
# https://github.com/tov/libffi-rs/pull/80
libffi-sys = { git = "https://github.com/fracek/libffi-rs.git", rev = "653781aa9b7a7ac1682e7f8cb405a2e90afc341d" }

