[workspace]
members = [
    "core",
    "observability",
    "node",
    "sdk",
    "erigon_dna",
    "starknet",
    "sink-common",
    "sink-webhook",
    "examples/starknet-simple",
]

[patch.crates-io]
revm = { git = "https://github.com/bluealloy/revm", rev = "afc3066" }
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "afc3066" }
