[workspace]
members = [
    "core",
    "observability",
    "node",
    "sdk",
    "starknet",
    "sink-common",
    "sink-webhook",
    "sink-mongo",
    "sink-parquet",
    "examples/starknet-simple",
]
