[workspace.package]
edition = "2021"
authors = ["Francesco Ceccon", "The Apibara contributors"]
repository = "https://github.com/apibara/dna"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = ["observability", "protocol", "common", "evm", "starknet"]

[workspace.dependencies]
assert_matches = "1.5.0"
anstyle = "1.0.1"
arrayvec = "0.7.2"
async-channel = "2.1.1"
async-compression = { version = "0.4.6", features = ["tokio", "zstd"] }
async-stream = "0.3.5"
async-trait = "0.1.57"
bytecheck = "0.6.12"
bytes = "1.5.0"
byteorder = "1.4.3"
byte-unit = "4.0.14"
clap = { version = "4.3.3", features = [
    "derive",
    "env",
    "cargo",
    "unicode",
    "color",
    "unstable-styles",
] }
ctrlc = { version = "3.2.3", features = ["termination"] }
deno_ast = { version = "0.31", features = ["cjs", "transpiling"] }
deno_core = "0.224.0"
deno_runtime = "0.130.0"
dirs = "4.0.0"
dotenvy = "0.15.7"
error-stack = "0.4.1"
flate2 = "1.0"
flatbuffers = { version = "23.5.26", features = ["serialize"] }
futures = "0.3.23"
futures-util = "0.3.26"
governor = "0.6.0"
hex = { version = "0.4.3", features = ["serde"] }
http = "0.2.9"
hyper = "0.14.20"
lazy_static = "1.4.0"
lru = "0.12.3"
jemallocator = { version = "0.5.0" }
memmap2 = "0.9.4"
mockall = "0.11.4"
nanoid = "0.4.0"
opentelemetry = { version = "0.18.0", features = [
    "trace",
    "metrics",
    "rt-tokio",
] }
opentelemetry-otlp = { version = "0.11.0", features = [
    "trace",
    "metrics",
    "grpc-tonic",
] }
pin-project = "1.0.12"
prost = "0.11.0"
prost-types = "0.11.0"
reqwest = { version = "0.11.16", default-features = false, features = [
    "json",
    "serde_json",
    "rustls-tls",
] }
regex = "1.9.1"
rkyv = { version = "0.7.44", features = ["validation"] }
roaring = "0.10.2"
rusqlite = "0.29.0"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.32"
tempfile = "3.3.0"
tempdir = "0.3.7"
testcontainers = { git = "https://github.com/fracek/testcontainers-rs.git", rev = "98a5557e" }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["sync", "net"] }
tokio-util = "0.7.4"
tonic = { version = "0.9.0", features = ["tls", "tls-roots", "prost"] }
tonic-build = "0.9.0"
tonic-health = "0.9.0"
tonic-reflection = "0.9.0"
tower = "0.4.13"
tracing = { version = "0.1.36", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
tracing-futures = { version = "0.2.5", features = ["tokio", "futures-03"] }
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.15", features = [
    "std",
    "env-filter",
    "json",
] }
tracing-tree = "0.2.2"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
warp = "0.3.5"
wiremock = "0.5.19"
url = "2.3"
