[workspace.package]
edition = "2021"
authors = ["Francesco Ceccon", "The Apibara contributors"]
repository = "https://github.com/apibara/dna"
license = "Apache-2.0"

[workspace]
members = [
    "core",
    "observability",
    "node",
    "sdk",
    "starknet",
    "sink-common",
    "sink-webhook",
    "sink-mongo",
    "sink-parquet",
    "sink-postgres",
    "examples/starknet-simple",
]

[workspace.dependencies]
assert_matches = "1.5.0"
anyhow = "1.0.66"
arrayvec = "0.7.2"
async-stream = "0.3.5"
async-trait = "0.1.57"
byteorder = "1.4.3"
byte-unit = "4.0.14"
clap = { version = "4.3.3", features = ["derive", "env", "cargo", "unicode"] }
ctrlc = { version = "3.2.3", features = ["termination"] }
dirs = "4.0.0"
dotenvy = "0.15.7"
futures = "0.3.23"
futures-util = "0.3.26"
hex = { version = "0.4.3", features = ["serde"] }
http = "0.2.9"
hyper = "0.14.20"
lazy_static = "1.4.0"
mockall = "0.11.4"
opentelemetry = { version = "0.18.0", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["trace", "metrics", "grpc-tonic"] }
pbjson = "0.5.1"
pbjson-build = "0.5.1"
pbjson-types = "0.5.1"
pin-project = "1.0.12"
prost = "0.11.0"
reqwest = { version = "0.11.16", default-features = false, features = ["serde_json", "rustls-tls"] }
serde = "1.0.155"
serde_json = "1.0.94"
# starknet = { git = "https://github.com/xJonathanLEI/starknet-rs", rev = "ca077d3104e11a59d873f79e6090f0ec8cb3fc58" }
starknet = { git = "https://github.com/fracek/starknet-rs", rev = "51ae3c8b560" }
thiserror = "1.0.32"
tempfile = "3.3.0"
tempdir = "0.3.7"
testcontainers = "0.14.0"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["sync"] }
tokio-util = "0.7.4"
tonic = { version = "0.9.0", features = ["tls", "tls-roots", "prost" ] }
tonic-build = "0.9.0"
tonic-health = "0.9.0"
tonic-reflection = "0.9.0"
tower = "0.4.13"
tracing = { version = "0.1.36", features = ["max_level_trace", "release_max_level_debug"] }
tracing-futures = { version = "0.2.5", features = ["tokio", "futures-03"] }
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.15", features = ["std", "env-filter"] }
tracing-tree = "0.2.2"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
warp = "0.3.5"

[patch.crates-io]
# Fixes related to copying file permissions/mode when building.
# Can be removed when PR have been merged and released.
# https://github.com/denoland/rusty_v8/pull/1244
v8 = { git = "https://github.com/fracek/rusty_v8.git", rev = "8140a1a6d7a8296d68dfcf7efb6f30b9f1ae04a" }
# https://github.com/tov/libffi-rs/pull/80
libffi-sys = { git = "https://github.com/fracek/libffi-rs.git", rev = "653781aa9b7a7ac1682e7f8cb405a2e90afc341d" }

