steps:
- label: ":nix: Checks"
  command: nix flake check

- wait

- label: ":rust: Build tests"
  command: nix build .#tests

- wait

- label: ":test_tube: Run tests"
  commands:
  - nix develop .#ci -c ci-test
  - nix develop .#ci -c ci-e2e-test

- wait

- group: ":rust: Build crate"
  steps:
  - label: "Build all crates"
    command: nix build .#all-crates

- wait

- group: ":rust: Build binaries"
  steps:
  - label: ":rust: Build binary {{ matrix.binary }}"
    command: nix build .#{{ matrix.binary }}
    matrix:
      setup:
        binary:
        - starknet
        - operator
        - sink-webhook
        - sink-mongo
        - sink-postgres
        - sink-parquet

- wait

- group: ":docker: Build images"
  steps:
  - label: ":docker: Build image {{ matrix.binary }}"
    commands:
    - nix build .#{{ matrix.binary }}-image
    - cp result {{ matrix.binary }}-image-amd64.tar.gz
    - buildkite-agent artifact upload {{ matrix.binary }}-image-amd64.tar.gz
    matrix:
      setup:
        binary:
        - starknet
        - operator
        - sink-webhook
        - sink-mongo
        - sink-postgres
        - sink-parquet

- label: ":pipeline:"
  if: build.branch == "main"
  command: buildkite-agent pipeline upload .buildkite/pipeline.release.yml
