env:
  DRY_RUN: false # set to true to stop publishing images

steps:
- group: ":quay: Publish images"
  steps:
  - label: ":quay: Publish image {{ matrix.binary }}"
    commands:
    - buildkite-agent artifact download {{ matrix.binary }}-image-amd64.tar.gz .
    - nix develop .#ci -c ci-publish-image {{ matrix.binary }}-image-amd64.tar.gz {{ matrix.binary }}
    matrix:
      setup:
        binary:
        - starknet
        - operator
        - sink-webhook
        - sink-mongo
        - sink-postgres
        - sink-parquet
    plugins:
    - docker-login#v2.1.0:
        username: apibara+buildkite
        password-env: APIBARA_DOCKER_LOGIN_PASSWORD
        server: quay.io
