[package]
name = "apibara-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "apibara"
path = "src/main.rs"
doc = false

[dependencies]
apibara-observability = { path = "../observability" }
apibara-sink-common = { path = "../sink-common" }
clap.workspace = true
color-eyre.workspace = true
colored = "2.0.4"
dirs.workspace = true
serde.workspace = true
tabled = "0.14.0"
tokio.workspace = true
