[package]
name = "apibara-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
hex = "0.4.3"
prost = "0.11.0"
prost-types = "0.11.1"
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs", rev = "ca077d3104e11a59d873f79e6090f0ec8cb3fc58" }
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
tonic = "0.8.0"
tracing = "0.1.36"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[build-dependencies]
tonic-build = "0.8.0"
