[package]
name = "apibara-dna-evm"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_dna_evm"
path = "src/lib.rs"

[[bin]]
name = "apibara-dna-evm"
path = "src/bin.rs"

[dependencies]
apibara-observability = { path = "../../observability" }
apibara-dna-common = { path = "../common" }
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
error-stack.workspace = true
ethers = "2.0.11"
flatbuffers.workspace = true
governor.workspace = true
hex.workspace = true
futures-util.workspace = true
roaring.workspace = true
tokio.workspace = true
tokio-util.workspace = true
starknet.workspace = true
tracing.workspace = true

[target.'cfg(not(windows))'.dependencies]
jemallocator.workspace = true
