version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    command: ["--web.enable-remote-write-receiver", "--config.file=/etc/prometheus.yml"]
    volumes:
    - ./prometheus-config.yml:/etc/prometheus.yml
    networks:
    - backend
    ports:
    - 9090:9090

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yml"]
    networks:
    - backend
    volumes:
    - ./tempo-config.yml:/etc/tempo.yml
    - tempo-data:/tmp/tempo
    ports:
    - 4318:4318

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    networks:
    - backend
    volumes:
    - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
    - 4317:4317

  grafana:
    image: grafana/grafana:latest
    networks:
    - backend
    volumes:
    - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
    - 4000:3000

networks:
  backend:

volumes:
  tempo-data:
  mimir-data:
