[package]
name = "apibara-indexer-script"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
apibara-indexer-runtime = { path = "../runtime" }
data-url = "0.2.0"
deno_ast.workspace = true
deno_core.workspace = true
deno_runtime.workspace = true
error-stack.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_v8 = "0.134.0"
tokio.workspace = true

[dev-dependencies]
assert_matches.workspace = true
tempfile.workspace = true
