[package]
name = "apibara-dna-protocol"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_dna_protocol"
path = "src/lib.rs"

[dependencies]
pbjson.workspace = true
pbjson-types.workspace = true
prost.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true
