[package]
name = "starknet-token-transfer-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.59"
# for protobuf definitions
apibara-core = { path = "../../core" }
apibara-starknet = { path = "../../starknet" }
apibara-node = { path = "../../node" }
tokio = { version = "1.20.1", features = ["full"] }
thiserror = "1.0.37"
prost = "0.11.0"
prost-types = "0.11.1"
hex = "0.4.3"
lazy_static = "1.4.0"
