[package]
name = "apibara-node"
version = "0.1.0"
edition = "2021"

[lib]
name = "apibara_node"
path = "src/lib.rs"

[[bin]]
name = "apibara-node"
path = "src/bin.rs"

[dependencies]
anyhow = "=1.0.59"
apibara-core = { path = "../core" }
arrayvec = "0.7.2"
async-trait = "0.1.57"
byteorder = "1.4.3"
clap = { version = "3.2.17", features = ["env", "unicode"] }
dirs = "4.0.0"
env_logger = "0.9.0"
futures = "0.3.23"
libmdbx = "0.1.7"
opentelemetry = { version = "0.18.0", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["trace", "metrics", "grpc-tonic"] }
pin-project = "1.0.12"
prost = "0.11.0"
prost-types = "0.11.1"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.10"
tokio-util = "0.7.4"
tracing = "0.1.36"
tracing-opentelemetry = "0.17.4"
tracing-subscriber = { version = "0.3.15", features = ["std", "env-filter"] }

[dev-dependencies]
assert_matches = "1.5.0"
env_logger = "0.9.0"
tempfile = "3.3.0"
