[package]
name = "apibara-transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.187.0"
serde_json = "1.0.96"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }

[dev-dependencies]
tempfile = "3.3.0"
