[package]
name = "apibara-sdk"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
apibara-core = { path = "../core" }
async-stream = "0.3.4"
async-trait = { workspace = true }
futures = { workspace = true }
futures-util = "0.3.26"
hex = { workspace = true }
http = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

