[package]
name = "example-starknet-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
apibara-core = { path = "../../core" }
apibara-sdk = { path = "../../sdk" }
chrono = "0.4.24"
hex = "0.4.3"
tokio = { version = "1.26.0", features = ["full"] }
tokio-stream = "0.1.12"
