[package]
name = "example-starknet-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
apibara-core = { path = "../../core" }
apibara-sdk = { path = "../../sdk" }
chrono = "0.4.24"
hex.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
