[package]
name = "example-starknet-simple"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
apibara-core = { path = "../../core" }
apibara-sdk = { path = "../../sdk" }
chrono = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
