[package]
name = "apibara-starknet"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_starknet"
path = "src/lib.rs"

[[bin]]
name = "apibara-starknet"
path = "src/bin.rs"

[dependencies]
anyhow = { workspace = true }
apibara-core = { path = "../core" }
apibara-node = { path = "../node" }
backoff = { workspace = true }
bloomfilter = "1.0.9"
byte-unit = "4.0.14"
byteorder = { workspace = true }
chrono = "0.4.22"
clap = { workspace = true }
ctrlc = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
pbjson-types = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
starknet = { workspace = true }
tempdir = "0.3.7"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { path = "../tonic-reflection-patched" }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = { workspace = true }
tracing-futures = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
env_logger = "0.9.0"
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
tempfile = "3.3.0"

[build-dependencies]
tonic-build = { workspace = true }
