[package]
name = "apibara-dna-starknet"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_dna_starknet"
path = "src/lib.rs"

[[bin]]
name = "apibara-dna-starknet"
path = "src/bin.rs"

[features]
default = ["jemalloc"]
jemalloc = ["dep:jemallocator"]

[dependencies]
apibara-observability = { path = "../observability" }
apibara-dna-common = { path = "../common" }
apibara-dna-protocol = { path = "../protocol" }
async-channel.workspace = true
async-trait.workspace = true
bytecheck.workspace = true
bytes.workspace = true
clap.workspace = true
error-stack.workspace = true
flatbuffers.workspace = true
governor.workspace = true
hex.workspace = true
futures-util.workspace = true
memmap2.workspace = true
prost.workspace = true
roaring.workspace = true
rkyv.workspace = true
tonic.workspace = true
tonic-reflection.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs", rev = "7153d0e42" }
tracing.workspace = true

[target.'cfg(not(windows))'.dependencies]
jemallocator.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
