[package]
name = "apibara-runner-kubernetes"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_runner_kubernetes"
path = "src/lib.rs"

[[bin]]
name = "apibara-runner-kubernetes"
path = "src/bin.rs"

[dependencies]
apibara-runner-common = { path = "../runner-common" }
apibara-observability = { path = "../../observability" }
apibara-operator = { path = "../../operator" }
clap.workspace = true
ctrlc.workspace = true
error-stack.workspace = true
k8s-openapi = { version = "0.18.0", features = ["v1_26", "api", "schemars"] }
kube = { version = "0.83.0", features = ["client", "derive", "runtime", "rustls-tls"], default-features = false }
thiserror.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tonic-reflection.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
hostname-validator = "1.1.1"
