name: Build all crates

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    name: Build all crates
    runs-on: "${{ inputs.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: apibara-public
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#all-crates -L --accept-flake-config
