name: Checks (on Linux)

on:
  workflow_call:

jobs:
  lint:
    name: Run linters and code checks
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: apibara-public
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check -L --accept-flake-config

  unit-test:
    name: Run unit tests
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: apibara-public
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#unit-tests -L --accept-flake-config

  integration-test:
    name: Run integration tests
    runs-on: warp-ubuntu-latest-x64-4x
    needs:
      - lint
      - unit-test
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: apibara-public
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#integration-tests -L --accept-flake-config
