apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: example-config
data:
  # AVNU exchange swap events, on Starknet Goerli testnet.
  filter.json: |
    {
      "header": { "weak": true },
      "events": [
        {
          "fromAddress": "0x06d8cd321dcbbf54512eab67c8a6849faf920077a3996f40bb4761adc4f021d2",
          "keys": ["0xe316f0d9d2a3affa97de1d99bb2aac0538e2666d0d8545545ead241ef0ccab"]
        }
      ]
    }

  transform.js: |
    // Return the batch as is
    export default function transform(batch) {
      return batch;
    }

  # A filter that's not valid and will cause the sink to break.
  brokenFilter.json: |
    {
      "invalidField": {}
    }

  # An invalid javascript file (syntax error)
  brokenTransform.js: |
    export default function transform(batch) {

  # Throw an exception
  throwingTransform.js: |
    export default function transform(batch) {
      throw new Error('Error inside transform');
    }
