[package]
name = "apibara-sink-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apibara-core = { path = "../core" }
apibara-sdk = { path = "../sdk" }
apibara-transformer = { path = "../transformer" }
async-trait = "0.1.68"
bytesize = {version = "1.1.0", features = ["serde"]}
clap = { version = "4.2.4", features = ["derive", "env"] }
ctrlc = { version = "3.2.3", features = ["termination"] }
etcd-client = { version = "0.11.1" }
exponential-backoff = "1.2.0"
prost = "0.11.9"
serde = "1.0.160"
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = "0.7.8"
tracing = "0.1.36"
